#!/usr/bin/env python3
"""Generate level-up evolution lookup tables from data/Evolutions.c."""

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPECIES_H = ROOT / "include/constants/species.h"
EVOLUTIONS_C = ROOT / "data/Evolutions.c"
OUT_C = ROOT / "src/field/level_up_evo_tables.c"
OUT_H = ROOT / "include/constants/generated/level_up_evo_tables.h"

SPECIES_RE = re.compile(r"#define\s+(SPECIES_[A-Z0-9_]+)\s+(\d+)")
MAX_SPECIES_COUNT_RE = re.compile(r"#define\s+MAX_SPECIES_INCLUDING_FORMS\b.*//\s*(\d+)")
BLOCK_RE = re.compile(r"\[(SPECIES_[A-Z0-9_]+)\]\s*=\s*\{", re.MULTILINE)
EVO_LEVEL_RE = re.compile(r"\{\s*EVO_LEVEL,\s*(\d+),\s*(SPECIES_[A-Z0-9_]+)\s*\}")


def load_species(path: Path) -> tuple[dict[str, int], int]:
    species: dict[str, int] = {}
    max_species = 0

    for line in path.read_text(encoding="utf-8").splitlines():
        count_match = MAX_SPECIES_COUNT_RE.match(line.strip())
        if count_match:
            max_species = int(count_match.group(1))
            continue

        match = SPECIES_RE.match(line.strip())
        if match:
            name, value = match.group(1), int(match.group(2))
            if "_START" in name or name.endswith("_H"):
                continue
            species[name] = value
            max_species = max(max_species, value)
            continue

    if max_species == 0 and species:
        max_species = max(species.values())

    return species, max_species


def parse_level_up_evolutions(path: Path) -> list[tuple[str, int, str]]:
    text = path.read_text(encoding="utf-8")
    evolutions: list[tuple[str, int, str]] = []

    for block in BLOCK_RE.finditer(text):
        species = block.group(1)
        start = block.end()
        next_block = BLOCK_RE.search(text, start)
        end = next_block.start() if next_block else len(text)
        chunk = text[start:end]

        for match in EVO_LEVEL_RE.finditer(chunk):
            level = int(match.group(1))
            target = match.group(2)
            evolutions.append((species, level, target))
            break

    return evolutions


def generate_tables(species_map: dict[str, int], max_species: int, evolutions: list[tuple[str, int, str]]):
    prevo = [0] * (max_species + 1)
    evo_target = [0] * (max_species + 1)
    min_stage_level = [1] * (max_species + 1)

    for source, level, target in evolutions:
        if source not in species_map or target not in species_map:
            continue
        src_id = species_map[source]
        tgt_id = species_map[target]
        if src_id > max_species or tgt_id > max_species:
            continue
        evo_target[src_id] = tgt_id
        if prevo[tgt_id] == 0:
            prevo[tgt_id] = src_id
        min_stage_level[tgt_id] = level

    return prevo, evo_target, min_stage_level


def write_header(path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """#ifndef CONSTANTS_GENERATED_LEVEL_UP_EVO_TABLES_H
#define CONSTANTS_GENERATED_LEVEL_UP_EVO_TABLES_H

#include "constants/species.h"

extern const u16 sLevelUpPrevo[];
extern const u16 sLevelUpEvoTarget[];
extern const u8 sLevelUpMinStageLevel[];

#endif
""",
        encoding="utf-8",
    )


def write_source(path: Path, max_species: int, prevo, evo_target, min_stage_level):
    path.parent.mkdir(parents=True, exist_ok=True)

    def fmt_u16_array(values):
        lines = ["    " + ", ".join(str(v) for v in values[i : i + 16]) + "," for i in range(0, len(values), 16)]
        return "\n".join(lines)

    def fmt_u8_array(values):
        lines = ["    " + ", ".join(str(v) for v in values[i : i + 16]) + "," for i in range(0, len(values), 16)]
        return "\n".join(lines)

    path.write_text(
        f"""#include "types.h"
#include "constants/species.h"
#include "constants/generated/level_up_evo_tables.h"

// Generated by scripts/gen_level_up_evo_tables.py — do not edit.

const u16 sLevelUpPrevo[MAX_SPECIES_INCLUDING_FORMS + 1] = {{
{fmt_u16_array(prevo)}
}};

const u16 sLevelUpEvoTarget[MAX_SPECIES_INCLUDING_FORMS + 1] = {{
{fmt_u16_array(evo_target)}
}};

const u8 sLevelUpMinStageLevel[MAX_SPECIES_INCLUDING_FORMS + 1] = {{
{fmt_u8_array(min_stage_level)}
}};
""",
        encoding="utf-8",
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--species-header", type=Path, default=SPECIES_H)
    parser.add_argument("--evolutions", type=Path, default=EVOLUTIONS_C)
    parser.add_argument("--out-c", type=Path, default=OUT_C)
    parser.add_argument("--out-h", type=Path, default=OUT_H)
    args = parser.parse_args()

    species_map, max_species = load_species(args.species_header)
    evolutions = parse_level_up_evolutions(args.evolutions)
    prevo, evo_target, min_stage_level = generate_tables(species_map, max_species, evolutions)

    # Pad to full species id range (forms share level-up lines when present in Evolutions.c).
    while len(prevo) <= max_species:
        prevo.append(0)
        evo_target.append(0)
        min_stage_level.append(1)

    write_header(args.out_h)
    write_source(args.out_c, max_species, prevo, evo_target, min_stage_level)
    print(f"Wrote {args.out_c} and {args.out_h} ({max_species + 1} species slots)")


if __name__ == "__main__":
    main()
